sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: CSprcItlpctYBL0tKNzscX7WNgPCPCm2lFNDUyxOTib8SSDO/G3szUTc5f5GkrXw1yrw3lcID2sSz/ddFK95tJpAqZyY5p/g2hYTyDStoAxd2TwKLs3/zBgt/HnJocAtTbnk5B8ieJbEtRAHBqCvTNEd1FecgTjqWpzsUQt4+wDcDdK/NI43cgqp55e9qMYdro4+Lt5yVxevLj56RQmASSXUtsLya00Y+6O2Q0vkny30GrO/0mlO+3gRT1uyHrerLPZCmvO4NOvHYAYrIvlImgGZIPVD0+k5eAQpYadJgxXBjoBgx4fAOeZuqnr8W9rGax6oan5uQT+cad1UNIlm2kSfOJgmGDEICVy2N1Qs4icIxaGA+fHxXiWWgwEHSZHEed9FJkh12S6Fq8QYP0py3xoz+5Z6fZ7GWM12jH0FvuQEz8q226kmvPNrlku0Y+Lx1hdzC5ZaZEbyfT24CNy2YIVpSFsOLJiLf9fetb4M0ANTajnK9WKYIyBlsAO/XuA7rxSA6cvj8JwWmT74rQId3aWm9VxlUqMcz1D6k1/H44DAD5KMpStahvBps0SSMrQZAwCaAiehNdsa58zicyR8q3D+0kATGFSL/IdHy4ONiyaHa2D0koKV45vQw55zqVC/oU4LGFI3cS47VXhkf9DVWd34+CHphM0QOpi7WMsyv3M=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Gaming-Table--Its-Votaries-and-Victims.-Volume-I--of-II-_466
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy